<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Summary</h3>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="https://via.placeholder.com/64x64" class="img-fluid rounded" alt="Vuze" />
                            </div>
                            <div class="col-md-6">
                                <?=$oStoreItem->label?>
                            </div>
                            <div class="col-md-2">
                                $ <?=$oStoreItem->price_sell?>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-4">
                                <b>Total</b>
                            </div>
                            <div class="col-md-6">

                            </div>
                            <div class="col-md-2">
                                <b>$ <?=$oStoreItem->price_sell?></b>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <form action="" method="POST">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Checkout</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <input type="radio" name="store_paymentmethod" value="prepay" checked>
                            <i class="fas fa-money-check-alt fa-2x"></i> <?=$this->translate('Prepay')?>
                        </li>
                        <li class="list-group-item">
                            <input type="radio" name="store_store" value="stripe">
                            <i class="fab fa-cc-stripe fa-2x"></i> <?=$this->translate('Stripe')?>
                        </li>
                        <li class="list-group-item">
                            <input type="radio" name="store_paypal" value="paypal">
                            <i class="fab fa-paypal fa-2x"></i> <?=$this->translate('Paypal')?>
                        </li>
                    </ul>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-success">Buy & Activate now</button>
                </div>
            </div>
        </form>
    </div>
</div>