<?php

if(isset($sStoreUrl)) { ?>
    <?php
    $aCategories = [];
    $aArticlesByCategory = [];
    foreach($aItems as $oArt) {
        if(isset($oArt->category_idfs)) {
            foreach ($oArt->category_idfs as $oCat) {
                if ($oCat->label != 'Store Item') {
                    $aCategories[$oCat->id] = $oCat;
                    if (!array_key_exists($oCat->id, $aArticlesByCategory)) {
                        $aArticlesByCategory[$oCat->id] = [];
                    }
                    $aArticlesByCategory[$oCat->id][$oArt->id] = $oArt;
                }
            }
        }
    }

    ?>
    <div class="alert alert-success">Connected to <?=$sStoreUrl?></div>

    <div class="row">
        <div class="col-md-12" style="display:inline-block; position: relative; box-sizing: border-box;">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://via.placeholder.com/1650x350" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>First slide label</h5>
                            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="https://via.placeholder.com/1650x350" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Second slide label</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="https://via.placeholder.com/1650x350" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Third slide label</h5>
                            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

    <?php
    foreach($aCategories as $oCat) { ?>
        <h2><?=$oCat->label?></h2>
                <?php
                $bFirst = true;
                $iCount = 1;
                foreach($aArticlesByCategory[$oCat->id] as $oArt) { ?>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <img src="https://via.placeholder.com/156x156" class="img-fluid rounded" alt="Vuze" />
                                    </div>
                                    <div class="col-md-6">
                                        <h3 class="card-title"><?=$oArt->label?></h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="/store/buy/<?=$oArt->id?>"class="btn btn-primary text-white">Buy for $ <?=$oArt->price_sell?></a>
                            </div>
                        </div>
                    </div>
                <?php } ?>
        <hr/>
    <?php
    }

    if(count($aCategories) == 0) {
        ?>
        <div class="alert alert-info">Currently no articles in store</div>
        <?php
    }
} else { ?>
<div class="alert alert-danger"><?=$sError?></div>
<?php
}
?>
<style>
    .d-block {
        height:350px;
    }
</style>
