docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - 'Quick Start': quick-start.md
  - Reference:
      - 'Options': options.md
site_name: oneplace-skeletonrequest
site_description: "onePlace Application Skeletonrequest Module"
repo_url: 'https://github.com/OnePlc/PLC_X_Skeletonrequest'
theme: bootstrap4
extra:
  project: onePlc